<a href="https://colab.research.google.com/github/carademelon/segundo_repositorio/blob/main/Cadena_de_markov.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#1. Datos del problema:
#Consideramos un laberinto de 6 casillas enumeradas donde la probabilidad de introducir al ratón
#en las casillas 1, 2 y 3 es el doble que en las casillas 4, 5 y 6. Una vez dentro del laberinto,
#el ratón se mueve a cualquier casilla contigua o se queda en la casilla en la que está con la misma probabilidad.

#Abstracción a una cadena de Markov:
#El laberinto puede ser modelado como una cadena de Markov, donde las casillas del laberinto representan los estados
#y la probabilidad de moverse de un estado a otro está dada por una matriz de transición.

# Vector de probabildades iniciales cumpliendo la condicional que:
#En las casillas 1,2,3 hay el doble de probabilidad a comparacion de las casillas 4,5,6
# En este caso hay un margen de error de .28 ....
v = np.array([2/9, 2/9, 2/9, 1/9, 1/9, 1/9])
print(np.sum(v))

#Matriz de transicion.
P = np.array([[1/3, 1/3, 0, 0, 0, 1/3],
              [1/4, 1/4, 1/4, 1/4, 0, 0],
              [0, 1/3, 1/3, 1/3, 0, 0],
              [0, 0, 1/3, 1/3, 1/3, 0],
              [0, 1/4, 0, 1/4, 1/4, 1/4],
              [1/3, 0, 0, 0, 1/3, 1/3]])

# Multiplicar v por P, P^2 y P^3
vxP = np.dot(v, P)#probabilidad de estar en cierta casilla en 1 paso
vxP2 = np.dot(v, np.linalg.matrix_power(P, 2))#Eleva la matriz a la 2 para saber la prob. de estar en cierta casiila en 2 pasos
vxP3 = np.dot(v, np.linalg.matrix_power(P, 3)) #Eleva la matriz a la 3 para saber la prob. de estar en cierta casilla en 3 pasos

# Imprimir los resultados
print("Matriz P:")
print(P)
print("\nMultiplicación de v y P: En un tiempo 1... :")
print(vxP)

print("\nMatriz P^2:")
print(np.linalg.matrix_power(P, 2))
print("\nMultiplicación de v y P^2: En un tiempo 2... ")
print(vxP2)

print("\nMatriz P^3:")
print(np.linalg.matrix_power(P, 3))
print("\nMultiplicación de v y P^3: En un tiempo 3... ")
print(vxP3)

1.0
Matriz P:
[[0.33333333 0.33333333 0.         0.         0.         0.33333333]
 [0.25       0.25       0.25       0.25       0.         0.        ]
 [0.         0.33333333 0.33333333 0.33333333 0.         0.        ]
 [0.         0.         0.33333333 0.33333333 0.33333333 0.        ]
 [0.         0.25       0.         0.25       0.25       0.25      ]
 [0.33333333 0.         0.         0.         0.33333333 0.33333333]]

Multiplicación de v y P: En un tiempo 1... :
[0.16666667 0.23148148 0.16666667 0.19444444 0.10185185 0.13888889]

Matriz P^2:
[[0.30555556 0.19444444 0.08333333 0.08333333 0.11111111 0.22222222]
 [0.14583333 0.22916667 0.22916667 0.22916667 0.08333333 0.08333333]
 [0.08333333 0.19444444 0.30555556 0.30555556 0.11111111 0.        ]
 [0.         0.19444444 0.22222222 0.30555556 0.19444444 0.08333333]
 [0.14583333 0.125      0.14583333 0.20833333 0.22916667 0.14583333]
 [0.22222222 0.19444444 0.         0.08333333 0.19444444 0.30555556]]

Multiplicación de v y P^2: E

In [ ]:
np.sum(v)


1.2857142857142856